"""added event_id to EventDays

Revision ID: 9a5e477fa3e5
Revises: 
Create Date: 2024-01-19 02:06:26.803103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5e477fa3e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_event_id', 'event', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_days', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event_id', type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
